### ISSUE TITLE
Rozsypané XML pokud modul neexistuje

### ISSUE THREAD

**Issue by JosefKuchar** [bakalari-api/bakalari-api#17]
Bakaláři mě fakt nepřestanou udivovat... U některých modulů se stane například toto:
```xml
ChybnĂ˝ poĹľadavek<?xml version="1.0" encoding="utf-8"?>
<error>
    <code>104</code>
    <message>prĂˇzdnĂ˝ vĂ˝sledek (chybnĂ© parametry?)</message>
    <result>01</result>
</error>
```
Nějaké nápady jak to ošetřit v dokumentaci?

**Comment by JosefKuchar** [comment]
Možná stačí ověřit jestli první znak je `<`

**Comment by vitkolos** [comment]
U mě to ukazuje `StrĂˇnku nelze zobrazit, protoĹľe doĹˇlo k vnitĹ™nĂ­ chybÄ› serveru.`. Takže ani takové ověření nepomůže... 😄 Každopádně – je třeba nějaké ošetřování/ověřování řešit? Prostě napíšeme, že to vrací něco čudného.

**Comment by JosefKuchar** [comment]
Však to taky tohle pokryje ne? K věci, mám dojem, že si škola může vybrat/připlatit za různé moduly, takže si člověk nikdy nemůže být jistý, co je aktivní

**Comment by vitkolos** [comment]
Jo máš pravdu...
To je fakt, ale závisí na tom, jestli něco děláš pro jednu školu, nebo pro celý svět. V druhém případě je určitě validace na místě. Na druhou stranu mě zaujalo, že naše škola nikde v Bakalářích (web) neukazuje akce, i když jsou funkční (modul akce vrací standardní výsledek).

**Comment by mariansam** [comment]
Jak posíláte request? Mně to funguje..
![image](https://user-images.githubusercontent.com/33497067/45383362-3bdc7800-b60b-11e8-870a-ab2eb33c96ef.png)

**Comment by JosefKuchar** [comment]
Tak zkus modul home. To enkodování je jedna věc, druhá je ta, že to není validní xml

**Comment by mariansam** [comment]
I u `home` mám to stejný výsledek. A co na tom není validní? Že je tam text ještě před tagem? V XML se moc nevyznám.

**Comment by JosefKuchar** [comment]
Jojo, občas se tam před to dostane `Chybný požadavek`, což z toho dělá to XML nevalidní

**Comment by vitkolos** [comment]
Každá škola to má jinak...

Výsledky mého výzkumu, který se týkal modulů, které naše škola nepoužívá nebo ke kterým nemám jako student přístup: [working-modules.txt](https://github.com/JosefKuchar/bakalari-api/files/2372556/working-modules.txt)

**Comment by vitkolos** [comment]
Tohle se týká API v1, které už je pravděpodobně na většině škol vypnuté, takže zavírám.
