### ISSUE TITLE
zobrazit: 2 - modul akce

### ISSUE THREAD

**Issue by mariansam** [bakalari-api/bakalari-api#22]
Dnes jsem na počítači otevřel Bakaláře a na úvodní stránce vidím, novou akci. Ale po otevření stránky Plán akcí jsem ji neviděl. Po poslání requestu jako mobilní aplikace jsem dostal
```xml
    <akce>
      <nazev>Divny event</nazev>
      <datum>20181115</datum>
      <cas/>
      <popis/>
      <zobrazit>2</zobrazit>
      <proucitele>Če</proucitele>
      <protridy/>
      <promistnosti/>
    </akce>
    <akce>
      <nazev>Normalni event</nazev>
      <datum>20190318</datum>
      <cas>10:00 - 11:40</cas>
      <popis/>
      <zobrazit>1</zobrazit>
      <proucitele>Lg, Šá, To</proucitele>
      <protridy>IIIP, IVP</protridy>
      <promistnosti/>
    </akce>
```
Nevíte, co u *Divny event* znamená `<zobrazit>2</zobrazit>`? Mobil mám rozbitý, takže nemůžu zjistit, zda tuto akci mobilní aplikace zobrazí.

**Comment by vitkolos** [comment]
Hodnota 2 určuje skrytí dané akce. Pánové z Bakalářů zde místo 0 (false) používají dvojku, což však není nijak překvapivé. My máme Plán akcí kompletně skrytý, proto máme všude dvojky. Ve tvém případě je event skrytý kvůli tomu, že je platný pouze pro jednoho učitele, studenti se tedy bez něj obejdou.

**Comment by mariansam** [comment]
Díky moc. Používat pro false dvojku je dle mě prasárna. Nechápal jsem, proč by měl být skrytý.

**Comment by JosefKuchar** [comment]
Tohle není všechno, už je moc dobře prozkoumané to, že appka a webová verze mají jiný backend, takže vznikají věci jako že je jiný rozvrh vidět na webu a v aplikaci, známky a tak 😃

**Comment by vitkolos** [comment]
@mariansam Nemáš zač, souhlasím s tebou, každopádně je to jejich věc. 🙂 Zavírám issue.

**Comment by JosefKuchar** [comment]
Teď si říkám, proč to vůbec v tom xml je, když se to ani nemá zobrazit... Neměl by tohle řešit backend?

**Comment by vitkolos** [comment]
Měl, mají to blbě dělané. Holt spoléhají na to, že o API nikdo neví.
