### ISSUE TITLE
Můj vlastní program

### ISSUE THREAD

**Issue by kokolem** [bakalari-api/bakalari-api#23]
Zdravím,

napsal jsem si python program, který mi ukáže co si z tašky vyndat a co si do ní na zítra přidat podle rozvrhu z Bakalářů. Můžete ho přidat přidat do Programy postavené na tomto API? Najdete ho [zde](https://github.com/kokolem/bakalari-next-day). Díky!

**Comment by JosefKuchar** [comment]
Díky 👍

**Comment by vitkolos** [comment]
@kokolem Můžeš ho tam přidat sám. 😉 Stačí ho nahrát do organizace přes nastavení.
