### ISSUE TITLE
Dokumentace k notifikacím

### ISSUE THREAD

**Issue by SoptikHa2** [bakalari-api/bakalari-api#27]
Notifikace jdou získat posláním POST requestu na

`adresa.bakalaru.cz/if/2/overview/notifications`

Uživatel se nepřihlašuje klasicky jako u ostatních endpointů, ale pomocí [Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). Uživatelské jméno je `ANDR`, heslo je token, který je používán při přihlašování u ostatních endpointů.

Basic Authentication funguje tak, že se pošle header `Authorization` s hodnotou `Basic <b64>`, kde `<b64>` je string `<jmeno>:<heslo>` zakódovaný do base64.

Vstup:

```
{
    "MessageType": "Overview.Notifications.Req",
    "classificationFrom": "20180101",
    "classificationTo": "20190103",
    "homeworksFrom": "20180101",
    "homeworksTo": "20190103"
}
```

Výstup:
```
{
    "ClassificationCount": 0,
    "HomeworksCount": 0,
    "KomensMessagesCount": 0,
    "MessageType": "Overview.Notifications.Resp"
}
```

Ještě je potřeba potvrdit, jestli je adresa endpointu totožná u všech škol.

**Comment by mariansam** [comment]
Potvrzuji, že endpoint je stejný u všech serverů, viz #18
