### ISSUE TITLE
Web Bakalářů – soubory

### ISSUE THREAD

**Issue by Czechball** [bakalari-api/bakalari-api#41]
Zdravím, podařilo se mi lokálně zprovoznit Bakaláře. Webové rozhraní mi sice nefunguje, ale mám všechny jeho soubory. Nevím, jestli to nějak extra pomůže, ale stáhnout si je můžete [zde](https://mega.nz/#!iYhGEAyT!e3yMfSnAbyshvDbIlqzYgLNXjG_9p5sALKtf0jiQWF4).

**Comment by Czechball** [comment]
tfw ani nevím jak to pojmenovat

**Comment by JosefKuchar** [comment]
Úplně si nejsem jistý, že je tohle legální :D

**Comment by vitkolos** [comment]
Záleží, kde ty soubory vzal... Každopádně jsem tam žádný zdrojový kód nenašel, tak fakt nevím.

**Comment by vakabus** [comment]
Já si tedy legalitou také nejsem moc jistý. Navíc, není zbytečné to vše někam nahrávat, když je poměrně jednoduché vše stáhnout z oficiálních zdrojů? ;) To umožnují už docela dlouho. Aktuálně se tam dá dostat takto:
bakalari.cz > Pro školy > Stažení programu

**Comment by Czechball** [comment]
Tohle je v podstatě nainstalované z oficiálních zdrojů, ale aktivované licencí, co jsem našel.

**Comment by backinpix125** [comment]
Ahoj, jde nějak získat demoverze učitelského profilu na bakaláři?
