### ISSUE TITLE
Android aplikace postavená na tomto API

### ISSUE THREAD

**Issue by FelyCZ** [bakalari-api/bakalari-api#43]
Zdravím,
píšu proto, abych vám poděkoval za svělou práci odvedenou při vytváření tohoto repa. Podařilo se mi díky vám propojit svou aplikaci na průměry známek pro studenty se systémem Bakaláři. Kupodivu i ten import je rychlejší než u jejich mobilní aplikace... :D
Odkaz na aplikaci je zde: [Průměr Známek](https://play.google.com/store/apps/details?id=cz.fely.weightedaverage)

Nyní pracuji na vytvoření kompletního a jednotného API pro Android v jazyce Kotlin. Pokud se mi to někdy podaří dokončit, budu vás zde informovat.

**Comment by FelyCZ** [comment]
Knihovna implementující toto API pro Android je zde k nalédnutí: [BakaAPI - GitLab](https://gitlab.com/FelyCZ/bakaapi)

**Comment by mvolfik** [comment]
Aplikace je v seznamu, API knihovna sice ne, ale to asi nevadí, protože APIv1 stejně nejspíš končí, viz #56 . Zavírám.
