### ISSUE TITLE
Konfigurace API

### ISSUE THREAD

**Issue by PetrVobornik** [bakalari-api/bakalari-api#47]
Mám několik otázek, jak to celé vlastně zprovoznit.

1. Je potřeba v nastavení Bakalářů podporu API někde aktivovat?
1. Nebo dokonce [zaplatit](https://www.bakalari.cz/Static/konektor)?
1. Funguje to i pro účty učitelů (typ V)?
1. Platí ještě toto API nebo už jen ta [verze 2](https://github.com/bakalari-api/bakalari-api/issues/39)?
1. Pokud je škola [zde](https://sluzby.bakalari.cz/api/v1/municipality), lze se na ni rovnou připojit, nebo s tím tento seznam nemá nic společného?
1. Není nějaká oficiální dokumentace k API přímo od Bakalářů? V jejich nápovědě jsem o existenci API nenašel ani zmínku.

Zkusil jsem vlastní implementaci v C# i [tuto](https://github.com/bakalari-api/python-token-generator/blob/master/mktoken3.py) v Pythonu, token to spočítalo shodně, leč i když to v obou případech [údaje](https://github.com/bakalari-api/bakalari-api/blob/master/vypocitani_tokenu.md) na výpočet tokenu vrátí, tak jakýkoli požadavek na data (třeba [akce](https://github.com/bakalari-api/bakalari-api/blob/master/moduly/akce.md) nebo [login](https://github.com/bakalari-api/bakalari-api/blob/master/moduly/login.md)) s tímto tokenem vrací &lt;result&gt;-1&lt;/result&gt;&lt;message&gt;Chyba přihlášení&lt;/message&gt;. V čem by mohla být chyba?

**Comment by Cvolton** [comment]
1. Jedná se o API, které používá oficiální mobilní aplikace a které existuje pouze pro její účely. Jelikož je to nejjednodušší způsob jak se připojit do systému z programů třetí strany, vytvořili jsme tuto neoficiální dokumentaci. Čili, pokud škola podporuje mobilní aplikaci, API bude fungovat.
2. ^
3. Funguje, akorát to tu není dokumentované, protože nikdo z nás není učitel.
4. Oficiální mobilní aplikace pro Android stále převážně používá verzi 1
5. Na všech školách v tomto seznamu bude API fungovat, jedná se o seznam používaný mobilní aplikací samotnou. Tím se ale nevylučuje možnost, že bude API fungovat na školách, které na tomto seznamu chybí.
6. Původně se jedná o API existující pouze pro interní potřeby mobilní aplikace, čili to nikde dokumentované nebude.

**Comment by Patrik-svobodik** [comment]
Taky jsem narazil na tu samou chybu. Fakt nevím, kde je problém.

**Comment by vitkolos** [comment]
Co se týče chyby od @Patrik-svobodik: https://github.com/bakalari-api/bakalari-api-v3/issues/7
Tohle issue zavírám, snad se to @PetrVobornik nakonec podařilo rozchodit.

**Comment by Patrik-svobodik** [comment]
API v3 už jsem rozchodil ale v1 mi pořád nejde. Protože dokumentace v3 ještě není komplétní, budu muset použít i v1.

**Comment by vitkolos** [comment]
Moc nevím, jak ti pomoct, ale pokud by pro tebe bylo PHP dobrý jazyk, tak jsem publikovat nějaký kód tady: https://github.com/bakalari-api/php-bakalari-utils

**Comment by vitkolos** [comment]
@Patrik-svobodik je něco, co ti v API v3 chybí?

**Comment by PatrikTheDev** [comment]
V současnou chvíli snad ani ne, jen odesílání komens a učitelské endpointy, ale k těm se nedostaneme asi nikdo. Povedlo se mi s v3 vydat iOS aplikaci (Maturanti), úplně jsem ji zapomněl přidat do seznamu aplikací.

**Comment by vitkolos** [comment]
No pokud se v aplikaci Bakaláři OnLine dají posílat zprávy Komens (což nevím, protože naše škola Komens nepoužívá), tak by to mělo nějak jít i přes API v3. K prozkoumání učitelských endpointů bychom potřebovali nějaký učitelský účet nebo nadšeného učitele informatiky. 😄 Aplikace vypadá pěkně, dobrá práce! 👍 (Můžeš ji přidat do readme v repozitáři API v3.)

**Comment by Lastaapps** [comment]
V API v3 ty endpointy na komens (a třeba odběr notifikací) jsou, ale jsou formou POST a PUT requestů, do jejichž obsahu se mi nepodařilo dostat.

A k v1, u nás na škole je mám za to už vypnutá, ani stará již nedostupná oficiální aplikace se nezvládla připojit, takže cokoli budete vyvíjet, dělejte s v3 (až na učitelské věci, no).

**Comment by PatrikTheDev** [comment]
Samozřejmě bych v1 k ničemu nepoužil, tento thread je více jak rok starý

**Comment by Lastaapps** [comment]
Jejda, to jsem trošku přehlédl. Pardon

**Comment by vitkolos** [comment]
Tohle issue zavírám. K těm chybějícím endpointům případně založte nové (v repozitáři bakalari-api-v3).
