### ISSUE TITLE
Windows klient pro Bakaláře, který využívá toto API

### ISSUE THREAD

**Issue by Nkaskaj** [bakalari-api/bakalari-api#48]
Dobrý den, nejedná se o bug v samotné dokumentaci, ale spíše o poděkování všem, kteří se na této dokumentaci podílí. Tento ročník maturuji z informačních technologií a jako maturitní práci jsem si vybral Windows klienta pro Bakaláře. 
Odkaz na klienta: https://github.com/Nkaskaj/BakalariClient

Program se budu snažit udržovat aktualizovaný a budu přidávat nové funkce.

**Comment by JosefKuchar** [comment]
Není zač, přece jen pro takové účely jsme to udělali. Přidal jsem toho klienta do našeho seznamu programů (37d6860c71b3f39cf1859ef046f4941820de5413). Normálně se na github dává i zdrojový kód a používá se gitová historie, ale v tomto případě chápu, proč tomu tak není. Přesto bych po vašem odmaturování ocenil zveřejnění zdrojových kódů

**Comment by Nkaskaj** [comment]
Děkuji za přidání. Zdrojový kód mám v plánu přidat, hned jak přidám všechny ostatní funkce.
