### ISSUE TITLE
XML Schema

### ISSUE THREAD

**Issue by JosefKuchar** [bakalari-api/bakalari-api#5]

**Comment by vitkolos** [comment]
O co jde? 😃

**Comment by JosefKuchar** [comment]
Je to definice jak má dané XML vypadat, dát se podle toho to XML zvalidovat a nejspíš se to může hodit i při parsování 😃[https://www.w3schools.com/xml/schema_intro.asp](https://www.w3schools.com/xml/schema_intro.asp) [https://www.w3.org/2001/XMLSchema](https://www.w3.org/2001/XMLSchema)

**Comment by vitkolos** [comment]
Jaký má toto issue účel? Pokud je jím poučení o XML, asi ho splnilo.

**Comment by mariansam** [comment]
Jde o to, aby @JosefKuchar nezapomněl, že chce udělat XML schema. Tak jsem to pochopil.

**Comment by JosefKuchar** [comment]
To, že by ke každému XML měla být ještě definice v podobě XSD

**Comment by JosefKuchar** [comment]
Při parsování je docela důležité vědět, jaký datový typ co má. Samozřejmě existují generátory jako třeba [https://www.freeformatter.com/xsd-generator.html](https://www.freeformatter.com/xsd-generator.html), ale z těch vyjde moc obecný výsledek, který je potřeba ještě upravit ;)

**Comment by vitkolos** [comment]
Obecný? Mě se líbil... 😁 Ale fakt by mě zajímalo, co je třeba na výsledku od Freeformatter upravovat. 🤔 
Jenom doplňuji, že když se k tvorbě XSD odhodláš (já to považuji za zbytečnou práci navíc 😅), bylo by fajn to dát před samotný příklad XML výstupu. Jenom ať to potom všude nepřehazujem. 😃

**Comment by JosefKuchar** [comment]
Strukturu to umí dobře, typy proměnných a "volitelnost!" jednotlivých elementů to ale nedokáže (ani nemá jak) poznat

**Comment by vitkolos** [comment]
Tohle se týká API v1, které už je pravděpodobně na většině škol vypnuté, takže zavírám.
