### ISSUE TITLE
nefunguje login i se správnými údaji

### ISSUE THREAD

**Issue by danbulant** [bakalari-api/bakalari-api#50]
chtěl jsem udělat klienta v node pro bakaláře (pro mého asistenta), avšak mi nefunguje přihlášení. Údaje jsou správné (když je zkopíruju na login, vše funguje).
Škola je na adrese `intranet.zscvrch.cz`.

```js

    genToken(){
        console.log("[password]" + this.salt + this.pswd);
        var hashedPassword = btoa(sha512(this.salt + this.pswd));
        console.log("[hashedPassword]" + hashedPassword);

        function dateToYMD(date) { //https://stackoverflow.com/a/43365158
            var d = date.getDate();
            var m = date.getMonth() + 1; //Month from 0 to 11
            var y = date.getFullYear();
            return '' + y + '' + (m <= 9 ? '0' + m : m) + '' + (d <= 9 ? '0' + d : d);
        }

        var tokenString = "*login*";
        tokenString += this.name;
        tokenString += "*pwd*";
        tokenString += hashedPassword;
        tokenString += "*sgn*ANDR";
        tokenString += dateToYMD(new Date());

        console.log("[string]" + tokenString);
        var token = btoa(sha512(tokenString));
        console.log("[token]" + token);
        token = token.replace("\\", "_")
            .replace("/", "_")
            .replace("+", "-");
        console.log("[tokenFixed]" + token);
        this.token = token;
    }
```
Tímto kódem generuji token, avšak při použití dostávám chybu přihlášení.

**Comment by mariansam** [comment]
Pokud umíš rozchodit Python, vyzkoušej https://github.com/bakalari-api/python-token-generator. Je tam verze jak pro Python 2, tak pro Python 3. Teď jsem to vyzkoušel, funguje to. Zítra se kouknu, co by mohlo být špatně na tvém JavaScriptu.

**Comment by danbulant** [comment]
Já jsem to psal přesne podle docs, a pak zkusil použít i knihovnu bakalari (je na npm), taky nefungovala.Python rozchoděný mám, takže pak vyzkouším (obě verze, jak 2 tak 3)On Jan 29, 2020 11:15 PM, Marian Šámal <notifications@github.com> wrote:Pokud umíš rozchodit Python, vyzkoušej https://github.com/bakalari-api/python-token-generator. Je tam verze jak pro Python 2, tak pro Python 3. Teď jsem to vyzkoušel, funguje to. Zítra se kouknu, co by mohlo být špatně na tvém JavaScriptu.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Sent via Migadu.com, world's easiest email hosting>

**Comment by mariansam** [comment]
Co má být v proměnných `this.salt` a `this.pswd`? Na třetím řádku vidím, že hashuješ tyto dvě proměnné. Měl by se hashovat salt, ikod, typ a heslo. Spojené za sebe jako jeden string.

**Comment by danbulant** [comment]
to je akorát špatně pojmenované.Proměnná this.salt obsahuje salt + ikod + typ a this.pswd obsahuje hesloOn Jan 30, 2020 9:57 AM, Marian Šámal <notifications@github.com> wrote:Co má být v proměnných this.salt a this.pswd? Na třetím řádku vidím, že hashuješ tyto dvě proměnné. Měl by se hashovat salt, ikod, typ a heslo. Spojené za sebe jako jeden string.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Sent via Migadu.com, world's easiest email hosting>

**Comment by vitkolos** [comment]
Tak si zkus z toho Pythonu postupně vracet všechny dílčí proměnné a mezivýpočty a podobně to udělej i ve své JS verzi. Pokud by ti mohla pomoci PHP verze generátoru tokenu, tak tu najdeš tady: https://github.com/bakalari-api/php-bakalari-utils/blob/master/utils/form.php

**Comment by danbulant** [comment]
Tak jsem vyzkoušel PHP verzi která teď funguje, takže to jdu zkusit předělat do JS

**Comment by danbulant** [comment]
Tak po trošce debugování jsem zjistil že mi to dává výrazně delší hash na heslo. V PHP to dá řetězec o 88 znacích, v JS o 172 znacích...
Přitom tam dělám přesně to stejné co v php:
`btoa(sha512(salt + ikod + typ + heslo))`, kde btoa je base64 encode

**Comment by matrn** [comment]
Podle mě `sha512()` by mělo vrátit printable output, takže není důvod z toho dělat base64.

**Comment by danbulant** [comment]
je to printable, ale i když ten atob dám pryč, vrací to 128 znaků místo 88 jak v PHP (které funguje)

**Comment by danbulant** [comment]
ale ten printable je akorát ascii reprezentace HEX, ten formát je jiný než to co se vrátí po base64

**Comment by matrn** [comment]
A co to je za knihovnu, která implementuje `sha512()`?

**Comment by danbulant** [comment]
Knihovny které jsou požíty:
```js
got = got (request)
sha512 = js-sha512
parser = fast-xml-parser
btoa = btoa
```
všechny jsou veřejně na NPM

**Comment by vitkolos** [comment]
Tak si asi zkus srovnat vstup a výstup pro ony funkce u PHP a JS. Jiné řešení mě už nenapadá.

**Comment by danbulant** [comment]
to právě jsem zkoušel, tak jsem taky přišel na pár z těch věcí, resp. že mi ten sha512 s btoa vrací špatný string a proto to nefunguje (formát je stejný, jen ten hash se liší)

**Comment by danbulant** [comment]
Tak jsem zjistil...
Bylo to nejspíše knihovnou, jakmile jsem změnil na defaultní crypto modul (již v node) tak to rovnou fungovalo.
Dodělám tu class a dám to jako lib pro ostatní (jediná js knihovna co je dostupná nefunguje)

**Comment by danbulant** [comment]
Knihovna pro JS je k dispozici: https://github.com/danbulant/bakalari.js
Teď už i funguje 😀
