### ISSUE TITLE
API v3

### ISSUE THREAD

**Issue by milankolecek** [bakalari-api/bakalari-api#51]
Zdravím.
Jak asi víte, nedávno vyšla nová aplikace. Snažil jsem se ji analyzovat a narazil jsem při tom na už 3. (!) verzi Bakaláři API. Zdá se mi, že je aplikace napsaná v dartu a do čitelné podoby se mi podařilo rekonstruovat pouze widget část. Aplikace navíc ignoruje systémovou proxy, takže se nedá snadno odposlouchávat.

Co jsem zatím objevil:
Aplikace implementuje jakýsi podivný OAUTH. Na adresu *baka*/api/login posílá widget POST request s form urlencoded tělem kde máme
client_id    ANDR
grant_type    refresh_token
refresh_token    ????

Bez client_id, nebi grant_type dostaneme
```
{
  "error": "invalid_client",
  "error_description": "Unknown Client or invalid grant type."
}
```
bez validního refresh_token
```
{
  "error": "invalid_grant"
}
```

Otázkou mi zůstává, jak se vůbec k refresh_tokenu dostaneme.

Následně jsem v souboru libapp.so našel mnoho dalších endpointů (tyto jsou navíc pod /api/3), pro představu:
/api/3/marks/what-if
/api/3/timetable/actual
bohužel nemám tušení, jak se do nich autentizovat.

Budu moc rád, pokud mi s analýzou pomůžete. Zatím jsem založil provizorní repozitář https://github.com/milankolecek/bakalari-api-v3, nicméně až bude analyzováno, udělal bych repozitář pro zjištěné věci sem pod https://github.com/bakalari-api/.

**Comment by mariansam** [comment]
Té [nové aplikace](https://play.google.com/store/apps/details?id=cz.bakalari.mobile), která má ještě horší hodnocení (2,5 hvězdiček, ehm) než [ta stará](https://play.google.com/store/apps/details?id=cz.impire.bakalari.student) (3.1 hvězdiček) jsem si nevšiml. Díky, kouknu na ni. Nějaká dobrá práce na koroprázdniny.

**Comment by milankolecek** [comment]
Kdybys na něco přišel, napiš, taky na tom zatím budu pracovat.

**Comment by milankolecek** [comment]
Tady je seznam všech informačních endpointů (tj. vše kromě loginu): https://github.com/milankolecek/bakalari-api-v3/blob/master/endpoints.md

**Comment by DanielKrasny** [comment]
Login je vyřešen (viz PR https://github.com/milankolecek/bakalari-api-v3/pull/1), zbytek je díky seznamu endpointů již snadný. Nemáte zač.

**Comment by vitkolos** [comment]
@milankolecek pokud bys ten repozitář teda mohl přesunout do naší organizace, tak by to bylo super. Už jsem tě sem pozval.

**Comment by milankolecek** [comment]
Přesunuto. Asi udělám pro takové logické celky toho API oddělené složky, ve kterých bude pro každý endpoint vlastní soubor. Co vy na to?

**Comment by vitkolos** [comment]
To možná ani nebude nutné, ale nechám to na tobě. Možná se můžeš zkusit přibližně řídit strukturou tohoto repozitáře.

**Comment by vitkolos** [comment]
Díky všem za dosud odvedenou práci, ale ještě to není všechno, protože u spousty modulů neznáme způsob, jakým se posílají parametry. Netuším, jak @DanielKrasny zjistil postup autentizace, ale podobným způsobem bude možné vyzkoumat i onen způsob zasílání parametrů. Issue zavírám, zbytek prosím řešme v [novém repozitáři](/bakalari-api/bakalari-api-v3).
