### ISSUE TITLE
Ukončení projektu bakaweb.tk

### ISSUE THREAD

**Issue by vakabus** [bakalari-api/bakalari-api#54]
Ahoj!

Nevím, jestli jste o mém projektu někdy slyšeli, ale už hooodně dávno jsem na střední kvůli počítání průměru známek vytvořil server bakaweb.tk. Tehdy u nás na škole nebyly veřejné průměry, ale API Bakalářů bylo (a asi i stále je) špatně navržené a leakují tam informace o váze známky.

Celý projekt je napsaný v Pythonu, konkrétně v Djangu. Je to teda už několikátá iterace, ale tahle vydržela běžet posledních několik let tak nějak sama. Pro hostování je ještě vše zabalené do Dockeru.

Už před nějakou dobou jsem na stránky dal varování, že budu muset projekt ukončit, že nemám motivaci ani energii se o to starat. Dokonce se mi jeden člověk ozval, ale radši si nakonec psal něco vlastního. Nic se ale nestalo. Takže když jsem teď kvůli jednomu malému patchi pushnul do repa a od GitHubu mi přišlo asi 20 emailů s varováním na používání starých knihoven s bezpečnostními dírami, tak nepovažuju za dobrý nápad to dále bez údržby používat.

Trošku mne ale mrzí jen tak to vše po skoro 6 letech zahodit. A je to škoda, protože i přes současnou situaci se za poslední týden přihlásilo 60 unikátních uživatelů.

**Protože se projektu už nechci věnovat, tak nabízím, že zájemci předám doménu, aby stávající uživatelé měli nějakou náhradu. Pokud by se našel někdo, kdo by měl chuť starat se o celý můj projekt (pak už spíš projekt zájemce), tak to určitě vítám a v takovém případě se nabízím, že budu nadále server provozovat u sebe za své náklady (za nic ale neručím).**

Podmínkou je, že bych rád, aby projekt přešel od studenta studentům. Nechci předávat doménu nebo dokonce dávat správu nad serverem někomu, kdo by chtěl službu zpoplatnit nebo komerčně využívat. Chtěl bych, aby služba, která pod doménou poběží, byla zaměřená na zpřijemnění života studentů.

Nabídka platí minimálně 14. dní od teď, tj. do 10.5.2020. Pokud do té doby nikdo neprojeví zájem, nahradím web statickou stránkou odkazující na README.md v tomhle projektu.

----

Repo: https://github.com/vakabus/bakaweb.tk

**Comment by ondraczsk** [comment]
Zrovna dělám podobnou webovou aplikaci v PHP, která bude mít za úkol z většiny nahradit původní webové bakaláře..
![Snímek obrazovky (497)](https://user-images.githubusercontent.com/13401278/80922967-d65d7200-8d80-11ea-8070-6cce400b702f.png)

**Comment by vakabus** [comment]
@ondraczsk Moc nevím, jak tvoji zprávu chápat. :sweat_smile: Jenom konstatuješ, že děláš něco podobného, nebo by ti dávalo smysl převzít doménu?

**Comment by ondraczsk** [comment]
Hele, jakože doména by byla zajímavá, přemýšlím jestli to mám hostovat na mém osobním webu nebo vytvořit doménu bakaweb.cz - .tk mi příjde taková nepěkná, ale zase je zdarma.. Zatím nevim, no :D

**Comment by vakabus** [comment]
Souhlasím, že .tk není zas tak hezká. :) Vznikla v době, kdy jsem za to nechtěl platit a pak už o ní vědělo příliš mnoho lidí na to, abych něco měnil. Jde mi spíš o to, aby stávající uživatelé měli kam jít. Takže ono i kdyby jsi měl vlastní doménu a já tam jenom udělal redirect, tak je to podle mne lepší než nic. :-) Já bych s tím byl určitě ok, tvůj projekt vypadá zajímavě.

**Comment by vakabus** [comment]
Tak jsem to ukončil. Kdyby jste někdo později o doménu stál, dejte vědět...

**Comment by ondraczsk** [comment]
Ohledně progressu u mém projektu :-) - Začal jsem to předělávat do React.js a vypadá to zatím dobře :D
